// Base URL for all UI assets stores in supabase storage
const SUPABASE_ASSET_URL = 'https://funqzsdhvrnloatkmipm.supabase.co/storage/v1/object/public/assets-ui'

/**
 * Centralised mapping of all UI icon assets used throughout the app.
    * bg -> background assets
    * light -> used in light theme
    * dark -> used in dark theme
 */
export const ICONS = {

    // Background assets
    bg: {
        bg: `${SUPABASE_ASSET_URL}/bg/bg.png`,
    },

    // Light mode assets
    light: {
        account: `${SUPABASE_ASSET_URL}/light-mode/account.png`,
        add: `${SUPABASE_ASSET_URL}/light-mode/add.png`,
        alltasks: `${SUPABASE_ASSET_URL}/light-mode/alltasks.png`,
        appearance: `${SUPABASE_ASSET_URL}/light-mode/appearance.png`,
        archive: `${SUPABASE_ASSET_URL}/light-mode/archive.png`,
        arrow: `${SUPABASE_ASSET_URL}/light-mode/arrow.png`,
        calm: `${SUPABASE_ASSET_URL}/light-mode/calm.png`,
        calmo: `${SUPABASE_ASSET_URL}/light-mode/calmo.png`,
        close: `${SUPABASE_ASSET_URL}/light-mode/close.png`,
        completed: `${SUPABASE_ASSET_URL}/light-mode/completed.png`,
        dashboard: `${SUPABASE_ASSET_URL}/light-mode/dashboard.png`,
        date: `${SUPABASE_ASSET_URL}/light-mode/date.png`,
        delete: `${SUPABASE_ASSET_URL}/light-mode/delete.png`,
        drafts: `${SUPABASE_ASSET_URL}/light-mode/drafts.png`,
        emails: `${SUPABASE_ASSET_URL}/light-mode/emails.png`,
        focus: `${SUPABASE_ASSET_URL}/light-mode/focus.png`,
        focuso: `${SUPABASE_ASSET_URL}/light-mode/focuso.png`,
        greyflag: `${SUPABASE_ASSET_URL}/light-mode/greyflag.png`,
        grid: `${SUPABASE_ASSET_URL}/light-mode/grid.png`,
        info: `${SUPABASE_ASSET_URL}/light-mode/info.png`,
        logo: `${SUPABASE_ASSET_URL}/light-mode/logo.png`,
        mail: `${SUPABASE_ASSET_URL}/light-mode/mail.png`,
        markcomplete: `${SUPABASE_ASSET_URL}/light-mode/markcomplete.png`,
        markincomplete: `${SUPABASE_ASSET_URL}/light-mode/markincomplete.png`,
        menuclose: `${SUPABASE_ASSET_URL}/light-mode/menuclose.png`,
        menuopen: `${SUPABASE_ASSET_URL}/light-mode/menuopen.png`,
        priority: `${SUPABASE_ASSET_URL}/light-mode/priority.png`,
        priorityo: `${SUPABASE_ASSET_URL}/light-mode/priorityo.png`,
        profile: `${SUPABASE_ASSET_URL}/light-mode/profile.png`,
        read: `${SUPABASE_ASSET_URL}/light-mode/read.png`,
        redflag: `${SUPABASE_ASSET_URL}/light-mode/redflag.png`,
        reply: `${SUPABASE_ASSET_URL}/light-mode/reply.png`,
        row: `${SUPABASE_ASSET_URL}/light-mode/row.png`,
        send: `${SUPABASE_ASSET_URL}/light-mode/send.png`,
        sendo: `${SUPABASE_ASSET_URL}/light-mode/sendo.png`,
        settings: `${SUPABASE_ASSET_URL}/light-mode/settings.png`,
        signout: `${SUPABASE_ASSET_URL}/light-mode/signout.png`,
        star: `${SUPABASE_ASSET_URL}/light-mode/star.png`,
        stressdetect: `${SUPABASE_ASSET_URL}/light-mode/stressdetection.png`,
        success: `${SUPABASE_ASSET_URL}/light-mode/success.png`,
        tasks: `${SUPABASE_ASSET_URL}/light-mode/tasks.png`,
        tick: `${SUPABASE_ASSET_URL}/light-mode/tick.png`,
        today: `${SUPABASE_ASSET_URL}/light-mode/today.png`,
        unarchive: `${SUPABASE_ASSET_URL}/light-mode/unarchive.png`,
        unread: `${SUPABASE_ASSET_URL}/light-mode/unread.png`,
        upcoming: `${SUPABASE_ASSET_URL}/light-mode/upcoming.png`,
        warning: `${SUPABASE_ASSET_URL}/light-mode/warning.png`,
        wellbeing: `${SUPABASE_ASSET_URL}/light-mode/wellbeing.png`,
        yellowflag: `${SUPABASE_ASSET_URL}/light-mode/yellowflag.png`,
   },

    // Dark mode assets
   dark: {
        account: `${SUPABASE_ASSET_URL}/dark-mode/account.png`,
        add: `${SUPABASE_ASSET_URL}/dark-mode/add.png`,
        alltasks: `${SUPABASE_ASSET_URL}/dark-mode/alltasks.png`,
        appearance: `${SUPABASE_ASSET_URL}/dark-mode/appearance.png`,
        archive: `${SUPABASE_ASSET_URL}/dark-mode/archive.png`,
        arrow: `${SUPABASE_ASSET_URL}/dark-mode/arrow.png`,
        calm: `${SUPABASE_ASSET_URL}/dark-mode/calm.png`,
        calmo: `${SUPABASE_ASSET_URL}/dark-mode/calmo.png`,
        close: `${SUPABASE_ASSET_URL}/dark-mode/close.png`,
        completed: `${SUPABASE_ASSET_URL}/dark-mode/completed.png`,
        dashboard: `${SUPABASE_ASSET_URL}/dark-mode/dashboard.png`,
        date: `${SUPABASE_ASSET_URL}/dark-mode/date.png`,
        delete: `${SUPABASE_ASSET_URL}/dark-mode/delete.png`,
        drafts: `${SUPABASE_ASSET_URL}/dark-mode/drafts.png`,
        emails: `${SUPABASE_ASSET_URL}/dark-mode/emails.png`,
        focus: `${SUPABASE_ASSET_URL}/dark-mode/focus.png`,
        focuso: `${SUPABASE_ASSET_URL}/dark-mode/focuso.png`,
        greyflag: `${SUPABASE_ASSET_URL}/dark-mode/greyflag.png`,
        grid: `${SUPABASE_ASSET_URL}/dark-mode/grid.png`,
        info: `${SUPABASE_ASSET_URL}/dark-mode/info.png`,
        logo: `${SUPABASE_ASSET_URL}/dark-mode/logo.png`,
        mail: `${SUPABASE_ASSET_URL}/dark-mode/mail.png`,
        markcomplete: `${SUPABASE_ASSET_URL}/dark-mode/markcomplete.png`,
        markincomplete: `${SUPABASE_ASSET_URL}/dark-mode/markincomplete.png`,
        menuclose: `${SUPABASE_ASSET_URL}/dark-mode/menuclose.png`,
        menuopen: `${SUPABASE_ASSET_URL}/dark-mode/menuopen.png`,
        priority: `${SUPABASE_ASSET_URL}/dark-mode/priority.png`,
        priorityo: `${SUPABASE_ASSET_URL}/dark-mode/priorityo.png`,
        profile: `${SUPABASE_ASSET_URL}/dark-mode/profile.png`,
        read: `${SUPABASE_ASSET_URL}/dark-mode/read.png`,
        redflag: `${SUPABASE_ASSET_URL}/dark-mode/redflag.png`,
        reply: `${SUPABASE_ASSET_URL}/dark-mode/reply.png`,
        row: `${SUPABASE_ASSET_URL}/dark-mode/row.png`,
        send: `${SUPABASE_ASSET_URL}/dark-mode/send.png`,
        sendo: `${SUPABASE_ASSET_URL}/dark-mode/sendo.png`,
        settings: `${SUPABASE_ASSET_URL}/dark-mode/settings.png`,
        signout: `${SUPABASE_ASSET_URL}/dark-mode/signout.png`,
        star: `${SUPABASE_ASSET_URL}/dark-mode/star.png`,
        stressdetect: `${SUPABASE_ASSET_URL}/dark-mode/stressdetection.png`,
        success: `${SUPABASE_ASSET_URL}/dark-mode/success.png`,
        tasks: `${SUPABASE_ASSET_URL}/dark-mode/tasks.png`,
        tick: `${SUPABASE_ASSET_URL}/dark-mode/tick.png`,
        today: `${SUPABASE_ASSET_URL}/dark-mode/today.png`,
        unarchive: `${SUPABASE_ASSET_URL}/dark-mode/unarchive.png`,
        unread: `${SUPABASE_ASSET_URL}/dark-mode/unread.png`,
        upcoming: `${SUPABASE_ASSET_URL}/dark-mode/upcoming.png`,
        warning: `${SUPABASE_ASSET_URL}/dark-mode/warning.png`,
        wellbeing: `${SUPABASE_ASSET_URL}/dark-mode/wellbeing.png`,
        yellowflag: `${SUPABASE_ASSET_URL}/dark-mode/yellowflag.png`,
   },
}