export const STRESS_PALETTE = {
    light: {
        low: {
            bg: '#f7f0f0',
            cardA: '#fcfaf7',
            cardB: '#fcfaf7',
            blankCard: '#ffffff',
            a: '#ffdab9',
            aHover: '#d5b69b',
            b: '#f0e9cf',
            bHover: '#aba593',
            icons: '#c5c8cd',
            iconsHover: '#b2b4b7',
            acc: '#291c19',
            accHover: '#443532',
        },
        mid: {
            bg: '#ede8e8',
            cardA: '#fcfaf7',
            cardB: '#fcfaf7',
            blankCard: '#f8fbff',
            a: '#e6e6fa',
            aHover: '#e6e6fa',
            b: '#bfe7d6',
            bHover: '#bfe7d6',
            icons: '#9caabd',
            iconsHover: '#9caabd',
            acc: '#1c2a3c',
            accHover: '#33455a',
        },
        high: {
            bg: '#eeeeee',
            cardA: '#fcfaf7',
            cardB: '#fcfaf7',
            blankCard: '#fcfaff',
            a: '#aaf0d1',
            aHover: '#aaf0d1',
            b: '#cfe6df',
            bHover: '#cfe6df',
            icons: '#a1aebc',
            iconsHover: '#a1aebc',
            acc: '#2e1f44',
            accHover: '#594165',
        },
    },
    
    dark: {
        low: {
            bg: '#f7f0f0',
            cardA: '#fcfaf7',
            cardB: '#fcfaf7',
            blankCard: '#ffffff',
            a: '#deb6ab',
            aHover: '#deb6ab9d',
            b: '#f2e1a6',
            bHover: '#f2e2a690',
            icons: '#7c828d',
            iconsHover: '#7c828d90',
            acc: '#291c19',
            accHover: '#443532',
        },
        mid: {
            bg: '#ede8e8',
            cardA: '#fcfaf7',
            cardB: '#fcfaf7',
            blankCard: '#f8fbff',
            a: '#b6d8e8',
            aHover: '#b6d8e8',
            b: '#bfe7d6',
            bHover: '#bfe7d6',
            icons: '#9caabd',
            iconsHover: '#9caabd',
            acc: '#1c2a3c',
            accHover: '#33455a',
        },
        high: {
            bg: '#dedcdc',
            cardA: '#fcfaf7',
            cardB: '#fcfaf7',
            blankCard: '#fcfaff',
            a: '#b8beeb',
            aHover: '#b8beeb',
            b: '#cfe6df',
            bHover: '#cfe6df',
            icons: '#a1aebc',
            iconsHover: '#a1aebc',
            acc: '#2e1f44',
            accHover: '#594165',
        },
    },
};