/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/app/**/*.{js,ts,jsx,tsx}",
        "./src/components/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            fontFamily: {
                AbrilFatface: ['Abril-Fatface', 'sans-serif'], //fall-back
                Roboto: ['Roboto', 'sans-serif'], //fall-back
            },
            colors: {
                light: {
                    low: {
                        a: '#deb6ab',
                        b: '#f2e1a6',
                        c: '#c4d9eb',
                        bg: '#f4f1e8',
                        card: '#f4f1e8',
                        icon: '#dce9f5',
                        textA: '#181818c2',
                        textB: '#353535',
                        textC: '#121212',
                        button: '#25030393',
                        buttonHover: '#632525a7',
                        blankCard: '#fffef9',
                    },
                    mid: {
                        a: '#b6d8e8',
                        b: '#bfe7d6',
                        c: '#c9c4eb',
                        bg: '#e5e4e1ff',
                        card: '#cfe3f6ff',
                        icon: '#dce9f5',
                        textA: '#181818c2',
                        textB: '#353535',
                        textC: '#121212',
                        button: '#0311257d',
                        buttonHover: 'rgba(28, 57, 99, 0.7)',
                        blankCard: '#f5f9ffff',
                    },
                    high: {
                        a: '#b8beeb',
                        b: '#cfe6df',
                        c: '#d3d7e0',
                        bg: '#f1f1f1',
                        card: '#dbceee',
                        icon: '#dce9f5',
                        textA: '#181818c2',
                        textB: '#353535',
                        textC: '#121212',
                        button: '#13052487',
                        buttonHover: '#381c58a3',
                        blankCard: '#f9f7ffff',
                    },
                },
                dark: {
                    low: {
                        a: '#deb6ab',
                        b: '#f2e1a6',
                        c: '#c4d9eb',
                        bg: '#f4f1e8',
                        card: '#f4f1e8',
                        icon: '#dce9f5',
                        textA: '#25030393',
                        textB: '#353535',
                        textC: '#121212',
                        button: '#25030393',
                        buttonHover: '#632525a7',
                        blankCard: '#fffef9',
                    },
                    mid: {
                        a: '#b6d8e8',
                        b: '#bfe7d6',
                        c: '#c9c4eb',
                        bg: '#e5e4e1ff',
                        card: '#cfe3f6ff',
                        icon: '#dce9f5',
                        textA: '#0311257d',
                        textB: '#353535',
                        textC: '#121212',
                        button: '#0311257d',
                        buttonHover: 'rgba(28, 57, 99, 0.7)',
                        blankCard: '#f5f9ffff',
                    },
                    high: {
                        a: '#b8beeb',
                        b: '#cfe6df',
                        c: '#d3d7e0',
                        bg: '#f1f1f1',
                        card: '#dbceee',
                        icon: '#dce9f5',
                        textA: '#13052487',
                        textB: '#353535',
                        textC: '#121212',
                        button: '#13052487',
                        buttonHover: '#381c58a3',
                        blankCard: '#f9f7ffff',
                    },
                },
            },
        },
    },
    plugins: [],
}

